version: '3'
services:
  proxy:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  backend:
    image: mz47/annabingo-backend:latest
    container_name: annabingo-backend
    restart: always
    ports:
      - "8000:8000"
  frontend:
    image: mz47/annabingo-frontend:latest
    container_name: annabingo-frontend
    restart: always
    ports:
      - "3000:3000"